/*
 * Qualtrics API
 * This is the API specification for Qualtrics platform.
 *
 * The version of the OpenAPI document: 3.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package pl.wtx.qualtrics.api.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import pl.wtx.qualtrics.api.client.model.CreateTransactionContactsImportRequestContactsInner;
import pl.wtx.qualtrics.api.client.model.CreateTransactionContactsImportRequestTransactionMeta;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import pl.wtx.qualtrics.api.client.invoker.JSON;

/**
 * 
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.13.0")
public class CreateTransactionContactsImportRequest {
  public static final String SERIALIZED_NAME_TRANSACTION_META = "transactionMeta";
  @SerializedName(SERIALIZED_NAME_TRANSACTION_META)
  @javax.annotation.Nullable
  private CreateTransactionContactsImportRequestTransactionMeta transactionMeta;

  public static final String SERIALIZED_NAME_CONTACTS = "contacts";
  @SerializedName(SERIALIZED_NAME_CONTACTS)
  @javax.annotation.Nonnull
  private List<CreateTransactionContactsImportRequestContactsInner> contacts = new ArrayList<>();

  public CreateTransactionContactsImportRequest() {
  }

  public CreateTransactionContactsImportRequest transactionMeta(@javax.annotation.Nullable CreateTransactionContactsImportRequestTransactionMeta transactionMeta) {
    this.transactionMeta = transactionMeta;
    return this;
  }

  /**
   * Get transactionMeta
   * @return transactionMeta
   */
  @javax.annotation.Nullable
  public CreateTransactionContactsImportRequestTransactionMeta getTransactionMeta() {
    return transactionMeta;
  }

  public void setTransactionMeta(@javax.annotation.Nullable CreateTransactionContactsImportRequestTransactionMeta transactionMeta) {
    this.transactionMeta = transactionMeta;
  }


  public CreateTransactionContactsImportRequest contacts(@javax.annotation.Nonnull List<CreateTransactionContactsImportRequestContactsInner> contacts) {
    this.contacts = contacts;
    return this;
  }

  public CreateTransactionContactsImportRequest addContactsItem(CreateTransactionContactsImportRequestContactsInner contactsItem) {
    if (this.contacts == null) {
      this.contacts = new ArrayList<>();
    }
    this.contacts.add(contactsItem);
    return this;
  }

  /**
   * A JSON array of JSON objects, where each object represents information about a contact. 
   * @return contacts
   */
  @javax.annotation.Nonnull
  public List<CreateTransactionContactsImportRequestContactsInner> getContacts() {
    return contacts;
  }

  public void setContacts(@javax.annotation.Nonnull List<CreateTransactionContactsImportRequestContactsInner> contacts) {
    this.contacts = contacts;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CreateTransactionContactsImportRequest createTransactionContactsImportRequest = (CreateTransactionContactsImportRequest) o;
    return Objects.equals(this.transactionMeta, createTransactionContactsImportRequest.transactionMeta) &&
        Objects.equals(this.contacts, createTransactionContactsImportRequest.contacts);
  }

  @Override
  public int hashCode() {
    return Objects.hash(transactionMeta, contacts);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CreateTransactionContactsImportRequest {\n");
    sb.append("    transactionMeta: ").append(toIndentedString(transactionMeta)).append("\n");
    sb.append("    contacts: ").append(toIndentedString(contacts)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("transactionMeta");
    openapiFields.add("contacts");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
    openapiRequiredFields.add("contacts");
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to CreateTransactionContactsImportRequest
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!CreateTransactionContactsImportRequest.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in CreateTransactionContactsImportRequest is not found in the empty JSON string", CreateTransactionContactsImportRequest.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!CreateTransactionContactsImportRequest.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `CreateTransactionContactsImportRequest` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : CreateTransactionContactsImportRequest.openapiRequiredFields) {
        if (jsonElement.getAsJsonObject().get(requiredField) == null) {
          throw new IllegalArgumentException(String.format("The required field `%s` is not found in the JSON string: %s", requiredField, jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      // validate the optional field `transactionMeta`
      if (jsonObj.get("transactionMeta") != null && !jsonObj.get("transactionMeta").isJsonNull()) {
        CreateTransactionContactsImportRequestTransactionMeta.validateJsonElement(jsonObj.get("transactionMeta"));
      }
      // ensure the json data is an array
      if (!jsonObj.get("contacts").isJsonArray()) {
        throw new IllegalArgumentException(String.format("Expected the field `contacts` to be an array in the JSON string but got `%s`", jsonObj.get("contacts").toString()));
      }

      JsonArray jsonArraycontacts = jsonObj.getAsJsonArray("contacts");
      // validate the required field `contacts` (array)
      for (int i = 0; i < jsonArraycontacts.size(); i++) {
        CreateTransactionContactsImportRequestContactsInner.validateJsonElement(jsonArraycontacts.get(i));
      };
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!CreateTransactionContactsImportRequest.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'CreateTransactionContactsImportRequest' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<CreateTransactionContactsImportRequest> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(CreateTransactionContactsImportRequest.class));

       return (TypeAdapter<T>) new TypeAdapter<CreateTransactionContactsImportRequest>() {
           @Override
           public void write(JsonWriter out, CreateTransactionContactsImportRequest value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public CreateTransactionContactsImportRequest read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of CreateTransactionContactsImportRequest given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of CreateTransactionContactsImportRequest
   * @throws IOException if the JSON string is invalid with respect to CreateTransactionContactsImportRequest
   */
  public static CreateTransactionContactsImportRequest fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, CreateTransactionContactsImportRequest.class);
  }

  /**
   * Convert an instance of CreateTransactionContactsImportRequest to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

