/*
 * Qualtrics API
 * This is the API specification for Qualtrics platform.
 *
 * The version of the OpenAPI document: 3.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package pl.wtx.qualtrics.api.client.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;

import java.io.IOException;
import com.google.gson.TypeAdapter;
import com.google.gson.JsonElement;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;

/**
 * Gets or Sets FilterType
 */
@JsonAdapter(FilterType.Adapter.class)
public enum FilterType {
  
  EMAIL("email"),
  
  FIRST_NAME("firstName"),
  
  LAST_NAME("lastName"),
  
  LANGUAGE("language"),
  
  PHONE("phone"),
  
  EXT_REF("extRef"),
  
  CREATED("created"),
  
  LAST_MODIFIED("lastModified"),
  
  IN_LIST("inList"),
  
  INFO_FIELD_STATE("infoFieldState"),
  
  EMBEDDED_DATA("embeddedData");

  private String value;

  FilterType(String value) {
    this.value = value;
  }

  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  public static FilterType fromValue(String value) {
    for (FilterType b : FilterType.values()) {
      if (b.value.equals(value)) {
        return b;
      }
    }
    throw new IllegalArgumentException("Unexpected value '" + value + "'");
  }

  public static class Adapter extends TypeAdapter<FilterType> {
    @Override
    public void write(final JsonWriter jsonWriter, final FilterType enumeration) throws IOException {
      jsonWriter.value(enumeration.getValue());
    }

    @Override
    public FilterType read(final JsonReader jsonReader) throws IOException {
      String value = jsonReader.nextString();
      return FilterType.fromValue(value);
    }
  }

  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
    String value = jsonElement.getAsString();
    FilterType.fromValue(value);
  }
}

