/*
 * Qualtrics API
 * This is the API specification for Qualtrics platform.
 *
 * The version of the OpenAPI document: 3.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package pl.wtx.qualtrics.api.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import pl.wtx.qualtrics.api.client.model.GetDirectoryContactEmailHistoryResponse;
import pl.wtx.qualtrics.api.client.model.GetDirectoryContactResponseHistoryResponse;
import pl.wtx.qualtrics.api.client.model.Meta;
import pl.wtx.qualtrics.api.client.model.Result10;



import java.io.IOException;
import java.lang.reflect.Type;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.ArrayList;
import java.util.Collections;
import java.util.HashSet;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapter;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.JsonPrimitive;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonSerializationContext;
import com.google.gson.JsonSerializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonArray;
import com.google.gson.JsonParseException;

import pl.wtx.qualtrics.api.client.invoker.JSON;

@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.13.0")
public class GetDirectoryContactHistoryResponse extends AbstractOpenApiSchema {
    private static final Logger log = Logger.getLogger(GetDirectoryContactHistoryResponse.class.getName());

    public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
        @SuppressWarnings("unchecked")
        @Override
        public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
            if (!GetDirectoryContactHistoryResponse.class.isAssignableFrom(type.getRawType())) {
                return null; // this class only serializes 'GetDirectoryContactHistoryResponse' and its subtypes
            }
            final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
            final TypeAdapter<GetDirectoryContactEmailHistoryResponse> adapterGetDirectoryContactEmailHistoryResponse = gson.getDelegateAdapter(this, TypeToken.get(GetDirectoryContactEmailHistoryResponse.class));
            final TypeAdapter<GetDirectoryContactResponseHistoryResponse> adapterGetDirectoryContactResponseHistoryResponse = gson.getDelegateAdapter(this, TypeToken.get(GetDirectoryContactResponseHistoryResponse.class));

            return (TypeAdapter<T>) new TypeAdapter<GetDirectoryContactHistoryResponse>() {
                @Override
                public void write(JsonWriter out, GetDirectoryContactHistoryResponse value) throws IOException {
                    if (value == null || value.getActualInstance() == null) {
                        elementAdapter.write(out, null);
                        return;
                    }

                    // check if the actual instance is of the type `GetDirectoryContactEmailHistoryResponse`
                    if (value.getActualInstance() instanceof GetDirectoryContactEmailHistoryResponse) {
                        JsonElement element = adapterGetDirectoryContactEmailHistoryResponse.toJsonTree((GetDirectoryContactEmailHistoryResponse)value.getActualInstance());
                        elementAdapter.write(out, element);
                        return;
                    }
                    // check if the actual instance is of the type `GetDirectoryContactResponseHistoryResponse`
                    if (value.getActualInstance() instanceof GetDirectoryContactResponseHistoryResponse) {
                        JsonElement element = adapterGetDirectoryContactResponseHistoryResponse.toJsonTree((GetDirectoryContactResponseHistoryResponse)value.getActualInstance());
                        elementAdapter.write(out, element);
                        return;
                    }
                    throw new IOException("Failed to serialize as the type doesn't match oneOf schemas: GetDirectoryContactEmailHistoryResponse, GetDirectoryContactResponseHistoryResponse");
                }

                @Override
                public GetDirectoryContactHistoryResponse read(JsonReader in) throws IOException {
                    Object deserialized = null;
                    JsonElement jsonElement = elementAdapter.read(in);

                    int match = 0;
                    ArrayList<String> errorMessages = new ArrayList<>();
                    TypeAdapter actualAdapter = elementAdapter;

                    // deserialize GetDirectoryContactEmailHistoryResponse
                    try {
                        // validate the JSON object to see if any exception is thrown
                        GetDirectoryContactEmailHistoryResponse.validateJsonElement(jsonElement);
                        actualAdapter = adapterGetDirectoryContactEmailHistoryResponse;
                        match++;
                        log.log(Level.FINER, "Input data matches schema 'GetDirectoryContactEmailHistoryResponse'");
                    } catch (Exception e) {
                        // deserialization failed, continue
                        errorMessages.add(String.format("Deserialization for GetDirectoryContactEmailHistoryResponse failed with `%s`.", e.getMessage()));
                        log.log(Level.FINER, "Input data does not match schema 'GetDirectoryContactEmailHistoryResponse'", e);
                    }
                    // deserialize GetDirectoryContactResponseHistoryResponse
                    try {
                        // validate the JSON object to see if any exception is thrown
                        GetDirectoryContactResponseHistoryResponse.validateJsonElement(jsonElement);
                        actualAdapter = adapterGetDirectoryContactResponseHistoryResponse;
                        match++;
                        log.log(Level.FINER, "Input data matches schema 'GetDirectoryContactResponseHistoryResponse'");
                    } catch (Exception e) {
                        // deserialization failed, continue
                        errorMessages.add(String.format("Deserialization for GetDirectoryContactResponseHistoryResponse failed with `%s`.", e.getMessage()));
                        log.log(Level.FINER, "Input data does not match schema 'GetDirectoryContactResponseHistoryResponse'", e);
                    }

                    if (match == 1) {
                        GetDirectoryContactHistoryResponse ret = new GetDirectoryContactHistoryResponse();
                        ret.setActualInstance(actualAdapter.fromJsonTree(jsonElement));
                        return ret;
                    }

                    throw new IOException(String.format("Failed deserialization for GetDirectoryContactHistoryResponse: %d classes match result, expected 1. Detailed failure message for oneOf schemas: %s. JSON: %s", match, errorMessages, jsonElement.toString()));
                }
            }.nullSafe();
        }
    }

    // store a list of schema names defined in oneOf
    public static final Map<String, Class<?>> schemas = new HashMap<String, Class<?>>();

    public GetDirectoryContactHistoryResponse() {
        super("oneOf", Boolean.FALSE);
    }

    public GetDirectoryContactHistoryResponse(Object o) {
        super("oneOf", Boolean.FALSE);
        setActualInstance(o);
    }

    static {
        schemas.put("GetDirectoryContactEmailHistoryResponse", GetDirectoryContactEmailHistoryResponse.class);
        schemas.put("GetDirectoryContactResponseHistoryResponse", GetDirectoryContactResponseHistoryResponse.class);
    }

    @Override
    public Map<String, Class<?>> getSchemas() {
        return GetDirectoryContactHistoryResponse.schemas;
    }

    /**
     * Set the instance that matches the oneOf child schema, check
     * the instance parameter is valid against the oneOf child schemas:
     * GetDirectoryContactEmailHistoryResponse, GetDirectoryContactResponseHistoryResponse
     *
     * It could be an instance of the 'oneOf' schemas.
     */
    @Override
    public void setActualInstance(Object instance) {
        if (instance instanceof GetDirectoryContactEmailHistoryResponse) {
            super.setActualInstance(instance);
            return;
        }

        if (instance instanceof GetDirectoryContactResponseHistoryResponse) {
            super.setActualInstance(instance);
            return;
        }

        throw new RuntimeException("Invalid instance type. Must be GetDirectoryContactEmailHistoryResponse, GetDirectoryContactResponseHistoryResponse");
    }

    /**
     * Get the actual instance, which can be the following:
     * GetDirectoryContactEmailHistoryResponse, GetDirectoryContactResponseHistoryResponse
     *
     * @return The actual instance (GetDirectoryContactEmailHistoryResponse, GetDirectoryContactResponseHistoryResponse)
     */
    @SuppressWarnings("unchecked")
    @Override
    public Object getActualInstance() {
        return super.getActualInstance();
    }

    /**
     * Get the actual instance of `GetDirectoryContactEmailHistoryResponse`. If the actual instance is not `GetDirectoryContactEmailHistoryResponse`,
     * the ClassCastException will be thrown.
     *
     * @return The actual instance of `GetDirectoryContactEmailHistoryResponse`
     * @throws ClassCastException if the instance is not `GetDirectoryContactEmailHistoryResponse`
     */
    public GetDirectoryContactEmailHistoryResponse getGetDirectoryContactEmailHistoryResponse() throws ClassCastException {
        return (GetDirectoryContactEmailHistoryResponse)super.getActualInstance();
    }

    /**
     * Get the actual instance of `GetDirectoryContactResponseHistoryResponse`. If the actual instance is not `GetDirectoryContactResponseHistoryResponse`,
     * the ClassCastException will be thrown.
     *
     * @return The actual instance of `GetDirectoryContactResponseHistoryResponse`
     * @throws ClassCastException if the instance is not `GetDirectoryContactResponseHistoryResponse`
     */
    public GetDirectoryContactResponseHistoryResponse getGetDirectoryContactResponseHistoryResponse() throws ClassCastException {
        return (GetDirectoryContactResponseHistoryResponse)super.getActualInstance();
    }

    /**
     * Validates the JSON Element and throws an exception if issues found
     *
     * @param jsonElement JSON Element
     * @throws IOException if the JSON Element is invalid with respect to GetDirectoryContactHistoryResponse
     */
    public static void validateJsonElement(JsonElement jsonElement) throws IOException {
        // validate oneOf schemas one by one
        int validCount = 0;
        ArrayList<String> errorMessages = new ArrayList<>();
        // validate the json string with GetDirectoryContactEmailHistoryResponse
        try {
            GetDirectoryContactEmailHistoryResponse.validateJsonElement(jsonElement);
            validCount++;
        } catch (Exception e) {
            errorMessages.add(String.format("Deserialization for GetDirectoryContactEmailHistoryResponse failed with `%s`.", e.getMessage()));
            // continue to the next one
        }
        // validate the json string with GetDirectoryContactResponseHistoryResponse
        try {
            GetDirectoryContactResponseHistoryResponse.validateJsonElement(jsonElement);
            validCount++;
        } catch (Exception e) {
            errorMessages.add(String.format("Deserialization for GetDirectoryContactResponseHistoryResponse failed with `%s`.", e.getMessage()));
            // continue to the next one
        }
        if (validCount != 1) {
            throw new IOException(String.format("The JSON string is invalid for GetDirectoryContactHistoryResponse with oneOf schemas: GetDirectoryContactEmailHistoryResponse, GetDirectoryContactResponseHistoryResponse. %d class(es) match the result, expected 1. Detailed failure message for oneOf schemas: %s. JSON: %s", validCount, errorMessages, jsonElement.toString()));
        }
    }

    /**
     * Create an instance of GetDirectoryContactHistoryResponse given an JSON string
     *
     * @param jsonString JSON string
     * @return An instance of GetDirectoryContactHistoryResponse
     * @throws IOException if the JSON string is invalid with respect to GetDirectoryContactHistoryResponse
     */
    public static GetDirectoryContactHistoryResponse fromJson(String jsonString) throws IOException {
        return JSON.getGson().fromJson(jsonString, GetDirectoryContactHistoryResponse.class);
    }

    /**
     * Convert an instance of GetDirectoryContactHistoryResponse to an JSON string
     *
     * @return JSON string
     */
    public String toJson() {
        return JSON.getGson().toJson(this);
    }
}

