/*
 * Qualtrics API
 * This is the API specification for Qualtrics platform.
 *
 * The version of the OpenAPI document: 3.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package pl.wtx.qualtrics.api.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.openapitools.jackson.nullable.JsonNullable;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import pl.wtx.qualtrics.api.client.invoker.JSON;

/**
 * MailingListMembershipDetails
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.13.0")
public class MailingListMembershipDetails {
  public static final String SERIALIZED_NAME_CONTACT_LOOKUP_ID = "contactLookupId";
  @SerializedName(SERIALIZED_NAME_CONTACT_LOOKUP_ID)
  @javax.annotation.Nullable
  private String contactLookupId;

  public static final String SERIALIZED_NAME_NAME = "name";
  @SerializedName(SERIALIZED_NAME_NAME)
  @javax.annotation.Nullable
  private String name;

  public static final String SERIALIZED_NAME_UNSUBSCRIBED = "unsubscribed";
  @SerializedName(SERIALIZED_NAME_UNSUBSCRIBED)
  @javax.annotation.Nullable
  private Boolean unsubscribed;

  public static final String SERIALIZED_NAME_UNSUBSCRIBE_DATE = "unsubscribeDate";
  @SerializedName(SERIALIZED_NAME_UNSUBSCRIBE_DATE)
  @javax.annotation.Nullable
  private Long unsubscribeDate;

  public static final String SERIALIZED_NAME_OWNER_ID = "ownerId";
  @SerializedName(SERIALIZED_NAME_OWNER_ID)
  @javax.annotation.Nullable
  private String ownerId;

  public MailingListMembershipDetails() {
  }

  public MailingListMembershipDetails contactLookupId(@javax.annotation.Nullable String contactLookupId) {
    this.contactLookupId = contactLookupId;
    return this;
  }

  /**
   * The contact&#39;s unique ID in the mailing list.
   * @return contactLookupId
   */
  @javax.annotation.Nullable
  public String getContactLookupId() {
    return contactLookupId;
  }

  public void setContactLookupId(@javax.annotation.Nullable String contactLookupId) {
    this.contactLookupId = contactLookupId;
  }


  public MailingListMembershipDetails name(@javax.annotation.Nullable String name) {
    this.name = name;
    return this;
  }

  /**
   * The name of the mailing list.
   * @return name
   */
  @javax.annotation.Nullable
  public String getName() {
    return name;
  }

  public void setName(@javax.annotation.Nullable String name) {
    this.name = name;
  }


  public MailingListMembershipDetails unsubscribed(@javax.annotation.Nullable Boolean unsubscribed) {
    this.unsubscribed = unsubscribed;
    return this;
  }

  /**
   * Whether the contact is unsubscribed.
   * @return unsubscribed
   */
  @javax.annotation.Nullable
  public Boolean getUnsubscribed() {
    return unsubscribed;
  }

  public void setUnsubscribed(@javax.annotation.Nullable Boolean unsubscribed) {
    this.unsubscribed = unsubscribed;
  }


  public MailingListMembershipDetails unsubscribeDate(@javax.annotation.Nullable Long unsubscribeDate) {
    this.unsubscribeDate = unsubscribeDate;
    return this;
  }

  /**
   * The date the contact opted out of this mailing list. Is set to null if the user has not opted out.
   * @return unsubscribeDate
   */
  @javax.annotation.Nullable
  public Long getUnsubscribeDate() {
    return unsubscribeDate;
  }

  public void setUnsubscribeDate(@javax.annotation.Nullable Long unsubscribeDate) {
    this.unsubscribeDate = unsubscribeDate;
  }


  public MailingListMembershipDetails ownerId(@javax.annotation.Nullable String ownerId) {
    this.ownerId = ownerId;
    return this;
  }

  /**
   * The ID of the user who owns the mailing list.
   * @return ownerId
   */
  @javax.annotation.Nullable
  public String getOwnerId() {
    return ownerId;
  }

  public void setOwnerId(@javax.annotation.Nullable String ownerId) {
    this.ownerId = ownerId;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    MailingListMembershipDetails mailingListMembershipDetails = (MailingListMembershipDetails) o;
    return Objects.equals(this.contactLookupId, mailingListMembershipDetails.contactLookupId) &&
        Objects.equals(this.name, mailingListMembershipDetails.name) &&
        Objects.equals(this.unsubscribed, mailingListMembershipDetails.unsubscribed) &&
        Objects.equals(this.unsubscribeDate, mailingListMembershipDetails.unsubscribeDate) &&
        Objects.equals(this.ownerId, mailingListMembershipDetails.ownerId);
  }

  private static <T> boolean equalsNullable(JsonNullable<T> a, JsonNullable<T> b) {
    return a == b || (a != null && b != null && a.isPresent() && b.isPresent() && Objects.deepEquals(a.get(), b.get()));
  }

  @Override
  public int hashCode() {
    return Objects.hash(contactLookupId, name, unsubscribed, unsubscribeDate, ownerId);
  }

  private static <T> int hashCodeNullable(JsonNullable<T> a) {
    if (a == null) {
      return 1;
    }
    return a.isPresent() ? Arrays.deepHashCode(new Object[]{a.get()}) : 31;
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class MailingListMembershipDetails {\n");
    sb.append("    contactLookupId: ").append(toIndentedString(contactLookupId)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    unsubscribed: ").append(toIndentedString(unsubscribed)).append("\n");
    sb.append("    unsubscribeDate: ").append(toIndentedString(unsubscribeDate)).append("\n");
    sb.append("    ownerId: ").append(toIndentedString(ownerId)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("contactLookupId");
    openapiFields.add("name");
    openapiFields.add("unsubscribed");
    openapiFields.add("unsubscribeDate");
    openapiFields.add("ownerId");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to MailingListMembershipDetails
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!MailingListMembershipDetails.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in MailingListMembershipDetails is not found in the empty JSON string", MailingListMembershipDetails.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!MailingListMembershipDetails.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `MailingListMembershipDetails` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if ((jsonObj.get("contactLookupId") != null && !jsonObj.get("contactLookupId").isJsonNull()) && !jsonObj.get("contactLookupId").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `contactLookupId` to be a primitive type in the JSON string but got `%s`", jsonObj.get("contactLookupId").toString()));
      }
      if ((jsonObj.get("name") != null && !jsonObj.get("name").isJsonNull()) && !jsonObj.get("name").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `name` to be a primitive type in the JSON string but got `%s`", jsonObj.get("name").toString()));
      }
      if ((jsonObj.get("ownerId") != null && !jsonObj.get("ownerId").isJsonNull()) && !jsonObj.get("ownerId").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `ownerId` to be a primitive type in the JSON string but got `%s`", jsonObj.get("ownerId").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!MailingListMembershipDetails.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'MailingListMembershipDetails' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<MailingListMembershipDetails> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(MailingListMembershipDetails.class));

       return (TypeAdapter<T>) new TypeAdapter<MailingListMembershipDetails>() {
           @Override
           public void write(JsonWriter out, MailingListMembershipDetails value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public MailingListMembershipDetails read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of MailingListMembershipDetails given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of MailingListMembershipDetails
   * @throws IOException if the JSON string is invalid with respect to MailingListMembershipDetails
   */
  public static MailingListMembershipDetails fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, MailingListMembershipDetails.class);
  }

  /**
   * Convert an instance of MailingListMembershipDetails to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

