/*
 * EX APIs
 * This is the external API specification for EX endpoints.
 *
 * The version of the OpenAPI document: 3.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package pl.wtx.qualtrics.api.client.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;

import java.io.IOException;
import com.google.gson.TypeAdapter;
import com.google.gson.JsonElement;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;

/**
 * Gets or Sets MetadataFilterTypes
 */
@JsonAdapter(MetadataFilterTypes.Adapter.class)
public enum MetadataFilterTypes {
  
  TEXT("text"),
  
  DATE("date"),
  
  NUMERIC("numeric");

  private String value;

  MetadataFilterTypes(String value) {
    this.value = value;
  }

  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  public static MetadataFilterTypes fromValue(String value) {
    for (MetadataFilterTypes b : MetadataFilterTypes.values()) {
      if (b.value.equals(value)) {
        return b;
      }
    }
    throw new IllegalArgumentException("Unexpected value '" + value + "'");
  }

  public static class Adapter extends TypeAdapter<MetadataFilterTypes> {
    @Override
    public void write(final JsonWriter jsonWriter, final MetadataFilterTypes enumeration) throws IOException {
      jsonWriter.value(enumeration.getValue());
    }

    @Override
    public MetadataFilterTypes read(final JsonReader jsonReader) throws IOException {
      String value = jsonReader.nextString();
      return MetadataFilterTypes.fromValue(value);
    }
  }

  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
    String value = jsonElement.getAsString();
    MetadataFilterTypes.fromValue(value);
  }
}

