/*
 * Qualtrics API
 * This is the API specification for Qualtrics platform.
 *
 * The version of the OpenAPI document: 3.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package pl.wtx.qualtrics.api.client.invoker;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapter;
import com.google.gson.internal.bind.util.ISO8601Utils;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.google.gson.JsonElement;
import io.gsonfire.GsonFireBuilder;
import io.gsonfire.TypeSelector;

import okio.ByteString;

import java.io.IOException;
import java.io.InputStream;
import java.io.InputStreamReader;
import java.io.StringReader;
import java.lang.reflect.Type;
import java.nio.charset.StandardCharsets;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.ParsePosition;
import java.time.LocalDate;
import java.time.OffsetDateTime;
import java.time.format.DateTimeFormatter;
import java.util.Date;
import java.util.Locale;
import java.util.Map;
import java.util.HashMap;

/*
 * A JSON utility class
 *
 * NOTE: in the future, this class may be converted to static, which may break
 *       backward-compatibility
 */
public class JSON {
    private static Gson gson;
    private static boolean isLenientOnJson = false;
    private static DateTypeAdapter dateTypeAdapter = new DateTypeAdapter();
    private static SqlDateTypeAdapter sqlDateTypeAdapter = new SqlDateTypeAdapter();
    private static OffsetDateTimeTypeAdapter offsetDateTimeTypeAdapter = new OffsetDateTimeTypeAdapter();
    private static LocalDateTypeAdapter localDateTypeAdapter = new LocalDateTypeAdapter();
    private static ByteArrayAdapter byteArrayAdapter = new ByteArrayAdapter();

    @SuppressWarnings("unchecked")
    public static GsonBuilder createGson() {
        GsonFireBuilder fireBuilder = new GsonFireBuilder()
        ;
        GsonBuilder builder = fireBuilder.createGsonBuilder();
        return builder;
    }

    private static String getDiscriminatorValue(JsonElement readElement, String discriminatorField) {
        JsonElement element = readElement.getAsJsonObject().get(discriminatorField);
        if (null == element) {
            throw new IllegalArgumentException("missing discriminator field: <" + discriminatorField + ">");
        }
        return element.getAsString();
    }

    /**
     * Returns the Java class that implements the OpenAPI schema for the specified discriminator value.
     *
     * @param classByDiscriminatorValue The map of discriminator values to Java classes.
     * @param discriminatorValue The value of the OpenAPI discriminator in the input data.
     * @return The Java class that implements the OpenAPI schema
     */
    private static Class getClassByDiscriminator(Map classByDiscriminatorValue, String discriminatorValue) {
        Class clazz = (Class) classByDiscriminatorValue.get(discriminatorValue);
        if (null == clazz) {
            throw new IllegalArgumentException("cannot determine model class of name: <" + discriminatorValue + ">");
        }
        return clazz;
    }

    static {
        GsonBuilder gsonBuilder = createGson();
        gsonBuilder.registerTypeAdapter(Date.class, dateTypeAdapter);
        gsonBuilder.registerTypeAdapter(java.sql.Date.class, sqlDateTypeAdapter);
        gsonBuilder.registerTypeAdapter(OffsetDateTime.class, offsetDateTimeTypeAdapter);
        gsonBuilder.registerTypeAdapter(LocalDate.class, localDateTypeAdapter);
        gsonBuilder.registerTypeAdapter(byte[].class, byteArrayAdapter);
        gsonBuilder.registerTypeAdapterFactory(new pl.wtx.qualtrics.api.client.model.BatchGetParticipantResponse.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new pl.wtx.qualtrics.api.client.model.BounceInfo.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new pl.wtx.qualtrics.api.client.model.CreateContactExportRequest.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new pl.wtx.qualtrics.api.client.model.CreateContactExportRequestEmbeddedData.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new pl.wtx.qualtrics.api.client.model.CreateContactExportResponse.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new pl.wtx.qualtrics.api.client.model.CreateContactResponse.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new pl.wtx.qualtrics.api.client.model.CreateDirectoryContactRequest.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new pl.wtx.qualtrics.api.client.model.CreateDirectoryContactResponse.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new pl.wtx.qualtrics.api.client.model.CreateIDPRequest.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new pl.wtx.qualtrics.api.client.model.CreateMailingListContactRequest.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new pl.wtx.qualtrics.api.client.model.CreateTransactionContactsImportRequest.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new pl.wtx.qualtrics.api.client.model.CreateTransactionContactsImportRequestContactsInner.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new pl.wtx.qualtrics.api.client.model.CreateTransactionContactsImportRequestTransactionMeta.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new pl.wtx.qualtrics.api.client.model.CreateTransactionContactsImportResponse.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new pl.wtx.qualtrics.api.client.model.DefaultEmptyResponse.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new pl.wtx.qualtrics.api.client.model.DefaultErrorResponse.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new pl.wtx.qualtrics.api.client.model.DeleteContactResponse.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new pl.wtx.qualtrics.api.client.model.EX360CopyRequest.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new pl.wtx.qualtrics.api.client.model.ElementsInner.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new pl.wtx.qualtrics.api.client.model.ElementsInner1.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new pl.wtx.qualtrics.api.client.model.ElementsInner2.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new pl.wtx.qualtrics.api.client.model.EmailHistory.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new pl.wtx.qualtrics.api.client.model.EmailHistoryBounceInfo.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new pl.wtx.qualtrics.api.client.model.Error.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new pl.wtx.qualtrics.api.client.model.EvaluatorImportBody.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new pl.wtx.qualtrics.api.client.model.EvaluatorRequest.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new pl.wtx.qualtrics.api.client.model.ExportCreationRequest.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new pl.wtx.qualtrics.api.client.model.ExportCreationResponse.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new pl.wtx.qualtrics.api.client.model.ExportStatusResponse.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new pl.wtx.qualtrics.api.client.model.GetContactExportFileResponse.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new pl.wtx.qualtrics.api.client.model.GetContactExportProgress.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new pl.wtx.qualtrics.api.client.model.GetContactHistoryResponse.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new pl.wtx.qualtrics.api.client.model.GetDirectoryContactEmailHistoryResponse.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new pl.wtx.qualtrics.api.client.model.GetDirectoryContactHistoryResponse.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new pl.wtx.qualtrics.api.client.model.GetDirectoryContactResponse.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new pl.wtx.qualtrics.api.client.model.GetDirectoryContactResponseHistoryResponse.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new pl.wtx.qualtrics.api.client.model.GetImportReportResponse.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new pl.wtx.qualtrics.api.client.model.GetImportReportResponseResults.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new pl.wtx.qualtrics.api.client.model.GetMailingListContactResponse.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new pl.wtx.qualtrics.api.client.model.GetRecordResponse.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new pl.wtx.qualtrics.api.client.model.GetTransactionContactsImportStatusResponse.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new pl.wtx.qualtrics.api.client.model.GetTransactionContactsImportSummaryResponse.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new pl.wtx.qualtrics.api.client.model.IDPField.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new pl.wtx.qualtrics.api.client.model.IDPNotFound.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new pl.wtx.qualtrics.api.client.model.IDPResponse.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new pl.wtx.qualtrics.api.client.model.ImportReportEntry.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new pl.wtx.qualtrics.api.client.model.ImportedDataProject.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new pl.wtx.qualtrics.api.client.model.JobId.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new pl.wtx.qualtrics.api.client.model.JobInfo.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new pl.wtx.qualtrics.api.client.model.JobResult.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new pl.wtx.qualtrics.api.client.model.JobResultsBucket.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new pl.wtx.qualtrics.api.client.model.ListContactsInContactListResponse.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new pl.wtx.qualtrics.api.client.model.ListDirectoryContactsResponse.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new pl.wtx.qualtrics.api.client.model.MailingListMembershipDetails.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new pl.wtx.qualtrics.api.client.model.Meta.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new pl.wtx.qualtrics.api.client.model.MetaInError.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new pl.wtx.qualtrics.api.client.model.MetadataFilter.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new pl.wtx.qualtrics.api.client.model.PageOfContacts.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new pl.wtx.qualtrics.api.client.model.PartialFailureResponse.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new pl.wtx.qualtrics.api.client.model.Participant.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new pl.wtx.qualtrics.api.client.model.ParticipantData.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new pl.wtx.qualtrics.api.client.model.ParticipantImportBody.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new pl.wtx.qualtrics.api.client.model.ParticipantRequest.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new pl.wtx.qualtrics.api.client.model.ParticipantResponse.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new pl.wtx.qualtrics.api.client.model.ParticipantsSearchRequest.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new pl.wtx.qualtrics.api.client.model.PostRecordsRequest.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new pl.wtx.qualtrics.api.client.model.ProjectIdsResponse.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new pl.wtx.qualtrics.api.client.model.ResponseHistory.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new pl.wtx.qualtrics.api.client.model.Result.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new pl.wtx.qualtrics.api.client.model.Result1.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new pl.wtx.qualtrics.api.client.model.Result10.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new pl.wtx.qualtrics.api.client.model.Result11.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new pl.wtx.qualtrics.api.client.model.Result12.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new pl.wtx.qualtrics.api.client.model.Result13.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new pl.wtx.qualtrics.api.client.model.Result14.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new pl.wtx.qualtrics.api.client.model.Result15.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new pl.wtx.qualtrics.api.client.model.Result16.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new pl.wtx.qualtrics.api.client.model.Result17.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new pl.wtx.qualtrics.api.client.model.Result18.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new pl.wtx.qualtrics.api.client.model.Result1Contacts.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new pl.wtx.qualtrics.api.client.model.Result1ContactsCount.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new pl.wtx.qualtrics.api.client.model.Result1Transactions.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new pl.wtx.qualtrics.api.client.model.Result1TransactionsCount.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new pl.wtx.qualtrics.api.client.model.Result2.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new pl.wtx.qualtrics.api.client.model.Result2Contacts.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new pl.wtx.qualtrics.api.client.model.Result2ContactsCount.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new pl.wtx.qualtrics.api.client.model.Result2Transactions.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new pl.wtx.qualtrics.api.client.model.Result2TransactionsCount.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new pl.wtx.qualtrics.api.client.model.Result3.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new pl.wtx.qualtrics.api.client.model.Result4.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new pl.wtx.qualtrics.api.client.model.Result5.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new pl.wtx.qualtrics.api.client.model.Result6.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new pl.wtx.qualtrics.api.client.model.Result7.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new pl.wtx.qualtrics.api.client.model.Result8.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new pl.wtx.qualtrics.api.client.model.Result9.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new pl.wtx.qualtrics.api.client.model.ResultContacts.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new pl.wtx.qualtrics.api.client.model.ResultTracking.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new pl.wtx.qualtrics.api.client.model.SearchDirectoryContactRequest.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new pl.wtx.qualtrics.api.client.model.SearchDirectoryContactResponse.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new pl.wtx.qualtrics.api.client.model.SegmentMembershipDetails.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new pl.wtx.qualtrics.api.client.model.SingleContact.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new pl.wtx.qualtrics.api.client.model.SingleContactLegacy.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new pl.wtx.qualtrics.api.client.model.SubjectData.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new pl.wtx.qualtrics.api.client.model.SubjectImportBody.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new pl.wtx.qualtrics.api.client.model.SubjectRequest.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new pl.wtx.qualtrics.api.client.model.UpdateContactResponse.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new pl.wtx.qualtrics.api.client.model.UpdateDirectoryContactResponse.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new pl.wtx.qualtrics.api.client.model.UpdateIDPRequest.CustomTypeAdapterFactory());
        gson = gsonBuilder.create();
    }

    /**
     * Get Gson.
     *
     * @return Gson
     */
    public static Gson getGson() {
        return gson;
    }

    /**
     * Set Gson.
     *
     * @param gson Gson
     */
    public static void setGson(Gson gson) {
        JSON.gson = gson;
    }

    public static void setLenientOnJson(boolean lenientOnJson) {
        isLenientOnJson = lenientOnJson;
    }

    /**
     * Serialize the given Java object into JSON string.
     *
     * @param obj Object
     * @return String representation of the JSON
     */
    public static String serialize(Object obj) {
        return gson.toJson(obj);
    }

    /**
     * Deserialize the given JSON string to Java object.
     *
     * @param <T>        Type
     * @param body       The JSON string
     * @param returnType The type to deserialize into
     * @return The deserialized Java object
     */
    @SuppressWarnings("unchecked")
    public static <T> T deserialize(String body, Type returnType) {
        try {
            if (isLenientOnJson) {
                JsonReader jsonReader = new JsonReader(new StringReader(body));
                // see https://google-gson.googlecode.com/svn/trunk/gson/docs/javadocs/com/google/gson/stream/JsonReader.html#setLenient(boolean)
                jsonReader.setLenient(true);
                return gson.fromJson(jsonReader, returnType);
            } else {
                return gson.fromJson(body, returnType);
            }
        } catch (JsonParseException e) {
            // Fallback processing when failed to parse JSON form response body:
            // return the response body string directly for the String return type;
            if (returnType.equals(String.class)) {
                return (T) body;
            } else {
                throw (e);
            }
        }
    }

    /**
    * Deserialize the given JSON InputStream to a Java object.
    *
    * @param <T>         Type
    * @param inputStream The JSON InputStream
    * @param returnType  The type to deserialize into
    * @return The deserialized Java object
    */
    @SuppressWarnings("unchecked")
    public static <T> T deserialize(InputStream inputStream, Type returnType) throws IOException {
        try (InputStreamReader reader = new InputStreamReader(inputStream, StandardCharsets.UTF_8)) {
        if (isLenientOnJson) {
            // see https://google-gson.googlecode.com/svn/trunk/gson/docs/javadocs/com/google/gson/stream/JsonReader.html#setLenient(boolean)
            JsonReader jsonReader = new JsonReader(reader);
            jsonReader.setLenient(true);
            return gson.fromJson(jsonReader, returnType);
            } else {
                return gson.fromJson(reader, returnType);
            }
        }
    }

    /**
     * Gson TypeAdapter for Byte Array type
     */
    public static class ByteArrayAdapter extends TypeAdapter<byte[]> {

        @Override
        public void write(JsonWriter out, byte[] value) throws IOException {
            if (value == null) {
                out.nullValue();
            } else {
                out.value(ByteString.of(value).base64());
            }
        }

        @Override
        public byte[] read(JsonReader in) throws IOException {
            switch (in.peek()) {
                case NULL:
                    in.nextNull();
                    return null;
                default:
                    String bytesAsBase64 = in.nextString();
                    ByteString byteString = ByteString.decodeBase64(bytesAsBase64);
                    return byteString.toByteArray();
            }
        }
    }

    /**
     * Gson TypeAdapter for JSR310 OffsetDateTime type
     */
    public static class OffsetDateTimeTypeAdapter extends TypeAdapter<OffsetDateTime> {

        private DateTimeFormatter formatter;

        public OffsetDateTimeTypeAdapter() {
            this(DateTimeFormatter.ISO_OFFSET_DATE_TIME);
        }

        public OffsetDateTimeTypeAdapter(DateTimeFormatter formatter) {
            this.formatter = formatter;
        }

        public void setFormat(DateTimeFormatter dateFormat) {
            this.formatter = dateFormat;
        }

        @Override
        public void write(JsonWriter out, OffsetDateTime date) throws IOException {
            if (date == null) {
                out.nullValue();
            } else {
                out.value(formatter.format(date));
            }
        }

        @Override
        public OffsetDateTime read(JsonReader in) throws IOException {
            switch (in.peek()) {
                case NULL:
                    in.nextNull();
                    return null;
                default:
                    String date = in.nextString();
                    if (date.endsWith("+0000")) {
                        date = date.substring(0, date.length()-5) + "Z";
                    }
                    return OffsetDateTime.parse(date, formatter);
            }
        }
    }

    /**
     * Gson TypeAdapter for JSR310 LocalDate type
     */
    public static class LocalDateTypeAdapter extends TypeAdapter<LocalDate> {

        private DateTimeFormatter formatter;

        public LocalDateTypeAdapter() {
            this(DateTimeFormatter.ISO_LOCAL_DATE);
        }

        public LocalDateTypeAdapter(DateTimeFormatter formatter) {
            this.formatter = formatter;
        }

        public void setFormat(DateTimeFormatter dateFormat) {
            this.formatter = dateFormat;
        }

        @Override
        public void write(JsonWriter out, LocalDate date) throws IOException {
            if (date == null) {
                out.nullValue();
            } else {
                out.value(formatter.format(date));
            }
        }

        @Override
        public LocalDate read(JsonReader in) throws IOException {
            switch (in.peek()) {
                case NULL:
                    in.nextNull();
                    return null;
                default:
                    String date = in.nextString();
                    return LocalDate.parse(date, formatter);
            }
        }
    }

    public static void setOffsetDateTimeFormat(DateTimeFormatter dateFormat) {
        offsetDateTimeTypeAdapter.setFormat(dateFormat);
    }

    public static void setLocalDateFormat(DateTimeFormatter dateFormat) {
        localDateTypeAdapter.setFormat(dateFormat);
    }

    /**
     * Gson TypeAdapter for java.sql.Date type
     * If the dateFormat is null, a simple "yyyy-MM-dd" format will be used
     * (more efficient than SimpleDateFormat).
     */
    public static class SqlDateTypeAdapter extends TypeAdapter<java.sql.Date> {

        private DateFormat dateFormat;

        public SqlDateTypeAdapter() {}

        public SqlDateTypeAdapter(DateFormat dateFormat) {
            this.dateFormat = dateFormat;
        }

        public void setFormat(DateFormat dateFormat) {
            this.dateFormat = dateFormat;
        }

        @Override
        public void write(JsonWriter out, java.sql.Date date) throws IOException {
            if (date == null) {
                out.nullValue();
            } else {
                String value;
                if (dateFormat != null) {
                    value = dateFormat.format(date);
                } else {
                    value = date.toString();
                }
                out.value(value);
            }
        }

        @Override
        public java.sql.Date read(JsonReader in) throws IOException {
            switch (in.peek()) {
                case NULL:
                    in.nextNull();
                    return null;
                default:
                    String date = in.nextString();
                    try {
                        if (dateFormat != null) {
                            return new java.sql.Date(dateFormat.parse(date).getTime());
                        }
                        return new java.sql.Date(ISO8601Utils.parse(date, new ParsePosition(0)).getTime());
                    } catch (ParseException e) {
                        throw new JsonParseException(e);
                    }
            }
        }
    }

    /**
     * Gson TypeAdapter for java.util.Date type
     * If the dateFormat is null, ISO8601Utils will be used.
     */
    public static class DateTypeAdapter extends TypeAdapter<Date> {

        private DateFormat dateFormat;

        public DateTypeAdapter() {}

        public DateTypeAdapter(DateFormat dateFormat) {
            this.dateFormat = dateFormat;
        }

        public void setFormat(DateFormat dateFormat) {
            this.dateFormat = dateFormat;
        }

        @Override
        public void write(JsonWriter out, Date date) throws IOException {
            if (date == null) {
                out.nullValue();
            } else {
                String value;
                if (dateFormat != null) {
                    value = dateFormat.format(date);
                } else {
                    value = ISO8601Utils.format(date, true);
                }
                out.value(value);
            }
        }

        @Override
        public Date read(JsonReader in) throws IOException {
            try {
                switch (in.peek()) {
                    case NULL:
                        in.nextNull();
                        return null;
                    default:
                        String date = in.nextString();
                        try {
                            if (dateFormat != null) {
                                return dateFormat.parse(date);
                            }
                            return ISO8601Utils.parse(date, new ParsePosition(0));
                        } catch (ParseException e) {
                            throw new JsonParseException(e);
                        }
                }
            } catch (IllegalArgumentException e) {
                throw new JsonParseException(e);
            }
        }
    }

    public static void setDateFormat(DateFormat dateFormat) {
        dateTypeAdapter.setFormat(dateFormat);
    }

    public static void setSqlDateFormat(DateFormat dateFormat) {
        sqlDateTypeAdapter.setFormat(dateFormat);
    }
}
