name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up JDK 8
        uses: actions/setup-java@v4
        with:
          java-version: '8'
          distribution: 'temurin'
          cache: 'maven'

      - name: Build with Maven
        run: |
          mvn -B clean package -DskipTests
          mvn -B javadoc:javadoc
          mvn -B source:jar

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          name: Release ${{ github.ref_name }}
          draft: false
          prerelease: false
          generate_release_notes: true
          files: |
            target/qualtrics-api-client-0.1.2.jar
            target/qualtrics-api-client-0.1.2-sources.jar
            target/qualtrics-api-client-0.1.2-javadoc.jar
            target/site/apidocs/**
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 